# -*- coding: UTF-8 -*-

VOCABULARY_GC_CORE_SUBJECT_THESAURUS = u'gc_core_subject_thesaurus'
VOCABULARY_ISO_TOPIC_CATEGORIES = u'iso_topic_categories'

GC_CORE_SUBJECT_THESAURUS = {
    'eng': {
        'AA': u'Arts, Music, Literature',
        'AG': u'Agriculture',
        'EC': u'Economics and Industry',
        'ET': u'Education and Training',
        'FM': u'Form descriptors',
        'GV': u'Government and Politics',
        'HE': u'Health and Safety',
        'HI': u'History and Archaeology',
        'IN': u'Information and Communications',
        'LB': u'Labour',
        'LN': u'Language and Linguistics',
        'LW': u'Law',
        'MI': u'Military',
        'NE': u'Nature and Environment',
        'PE': u'Persons',
        'PR': u'Processes',
        'SO': u'Society and Culture',
        'ST': u'Science and Technology',
        'TR': u'Transport',
        },
    'fra': {
        'AA': u'Arts, musique, littérature',
        'AG': u'Agriculture',
        'EC': u'Économie et industrie',
        'ET': u'Éducation et formation',
        'GV': u'Gouvernement et vie politique',
        'HE': u'Santé et sécurité',
        'HI': u'Histoire et archéologie',
        'IN': u'Information et communication',
        'LB': u'Travail et emploi',
        'LN': u'Langue et linguistique',
        'LW': u'Droit',
        'MI': u'Histoire et science militaire',
        'NE': u'Nature et environnement',
        'PE': u'Personnes',
        'PR': u'Liens et fonctions',
        'SO': u'Société et culture',
        'ST': u'Sciences et technologie',
        'TR': u'Transport',
        },
    }

ISO_TOPIC_CATEGORIES = {
    'eng': [
        u"farming",
        u"biota",
        u"boundaries",
        u"climatologyMeteorologyAtmosphere",
        u"economy",
        u"elevation",
        u"environment",
        u"geoscientificInformation",
        u"health",
        u"imageryBaseMapsEarthCover",
        u"intelligenceMilitary",
        u"inlandWaters",
        u"location",
        u"oceans",
        u"planningCadastre",
        u"society",
        u"structure",
        u"transportation",
        u"utilitiesCommunication",
        ],
    'fra': [
        u"agriculture",
        u"biote",
        u"frontières",
        u"climatologieMétéorologieAtmosphère",
        u"économie",
        u"élévation",
        u"environnement",
        u"informationGéoscientifique",
        u"santé",
        u"imagerieCarteDeBaseCouvertureTerrestre",
        u"renseignementsMilitaires",
        u"eauxIntérieures",
        u"localisation",
        u"océans",
        u"aménagementCadastre",
        u"société",
        u"structures",
        u"transport",
        u"servicesCommunication"
        ],
    }
