name: Check types
on: [workflow_call, workflow_dispatch]
env:
  NODE_VERSION: '18'

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    container:
      image: opendatacanada/ckan-pytest  # primary executor
    steps:
      - name: Install Node
        run: |
          apk add nodejs npm
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout Repository (${{ github.ref_name }})
        id: gitcheckout
        run: |
          cd /srv/app/src/ckanext-canada
          git fetch origin
          git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
          git fetch
          git pull
          source /srv/app/venv/bin/activate
          pip install -e .
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          python3 setup.py develop
          pip install -e 'git+https://github.com/open-data/ckanext-cloudstorage.git@canada-v2.10#egg=ckanext-cloudstorage' -r 'https://raw.githubusercontent.com/open-data/ckanext-cloudstorage/canada-v2.10/requirements.txt'
          cd /srv/app
      - name: Install Node Dependencies
        if: steps.gitcheckout.outcome == 'success'
        run: |
          cd /srv/app/src/ckanext-canada
          npm ci
      - name: Check Types
        if: steps.gitcheckout.outcome == 'success'
        run: |
          export PYTHONPATH="${PYTHONPATH}:/srv/app/lib/python3.9/site-packages:/srv/app/src/ckanext-citeproc"
          source /srv/app/venv/bin/activate
          cd /srv/app/src/ckanext-canada
          npx pyright
