name: Service Inventory Release Listener
on:
  issues:
    types: [opened]

jobs:
  make_pr:
    if: startsWith(github.event.issue.title, '[SI-RELEASE]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Ref Data Generation
        run: |
          cd bin;
          python service_generate_reference_data.py;

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            build(pd): service inventory;

            - Auto build ref data from issue ${{ github.event.issue.number }}.
          branch: "si-release/${{ github.event.issue.number }}"
          title: "[SI-RELEASE] Issue #${{ github.event.issue.number }}"
          body: |
            Newly generated reference data for Service Inventory.

            This PR was created automatically from issue #${{ github.event.issue.number }}

            cc: @ge-tbs
          reviewers: JVickery-TBS, RabiaSajjad
